# Generated by Django 3.0.5 on 2020-05-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='solve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='time',
            field=models.DateTimeField(default='2020-05-02 13:30:27'),
        ),
    ]
