# Generated by Django 3.0.5 on 2020-05-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_website', '0002_auto_20200502_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('src', models.TextField()),
                ('time', models.DateTimeField(default='2020-05-04 11:29:34')),
                ('delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='time',
            field=models.DateTimeField(default='2020-05-04 11:29:34'),
        ),
    ]
